name: Application SmartHotel360

on: workflow_dispatch

env:
  RG_NAME: rg-test-tdf
  LOCATION: westeurope
  SERVER_NAME_DB: smh360mysql40406cc
  DB_NAME: hotel_coupon
  USER_NAME: sqladmin
  PASSWORD: P2ssw0rd@123
  PLAN_NAME: smh360plan
  SITE_NAME: smh360webd4041cc

jobs:
  Build-App:
    runs-on: ubuntu-20.04
    steps:

      - name: Repuperation du repo
        uses: actions/checkout@v2

      - name: Perform Scan CredScan & Java
        uses: ShiftLeftSecurity/scan-action@master
        with:
          type: "credscan,java"

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Creation du package ROOT.war avec Maven
        run: |
          mvn --batch-mode --update-snapshots verify

      - name: Copie du fichier artefacts ROOT.war 
        run: | 
          mkdir warfile && cp target/*.war warfile

      - name: Publication du fichier ROOT.war en artefact  
        uses: actions/upload-artifact@v2
        with:
          name: Package-WAR
          path: warfile

  Deploy-App:
    runs-on: ubuntu-20.04
    needs: Build-App
    steps:

      - name: Creation dossier artifact
        run: |
          mkdir warfile

      - name: Recuperation des artefacts
        uses: actions/download-artifact@v2
        with:
          name: Package-WAR
          path: warfile

      - name: Azure Login
        uses: Azure/login@v1
        with:    
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploiement de l'application JAVA
        uses: azure/webapps-deploy@v2
        id: deploy-to-azure
        with:
          app-name: ${{ env.SITE_NAME }}
          package: ./warfile/ROOT.war 
         
            