name: application

on: workflow_dispatch

jobs:
  Build-App:
      runs-on: ubuntu-20.04
      steps:

        - name: Repuperation du repo
          uses: actions/checkout@v2

        - name: Setup Java
          uses: actions/setup-java@v1
          with:
            java-version: 1.8

        - name: Creation du package ROOT.war avec Maven
          run: mvn --batch-mode --update-snapshots verify

        - name: Copie du fichier artefacts ROOT.war 
          run: mkdir warfile && cp target/*.war warfile

        - name: Publication du fichier ROOT.war en artefact  
          uses: actions/upload-artifact@v2
          with:
            name: Package-WAR
            path: warfile               