name: Deploiement SmartHotel360

on:
  push:
    branches: [main]

jobs:
  IaC:
    runs-on: ubuntu-20.04

    steps:
      - name: check Bicep
        run: |
          az bicep -h

      - name: recuperation du repository
        uses: actions/checkout@v2

      - name: deploiemenent IaC
        run : |
          az deployment sub create -f ./bicep/main.bicep -l westeurope
        
