name: Deploiement SmartHotel360

on: workflow_dispatch

env:
# c'est une demonstration -> mettre ces variables dans le service "Secrets" de GitHub ex: ${{ secrets.RG_NAME}}  
  RG_NAME: rg-test-tdf
  LOCATION: westeurope
  SERVER_NAME_DB: smh360mysql40406cc
  DB_NAME: hotel_coupon
  USER_NAME: sqladmin
  PASSWORD: P2ssw0rd@123
  PLAN_NAME: smh360plan
  SITE_NAME: smh360webd4041cc

jobs:
  Build-IaC:
    runs-on: ubuntu-20.04

    steps:
      - name: recuperation du repository
        uses: actions/checkout@v2

      - name: build json
        run: |
          az bicep build --files ./bicep/main.bicep

      - name: Artifacts json
        uses: actions/upload-artifact@v1
        with:
          name: arm_template
          path: ./bicep/main.json
  Ckeck-IaC:
    needs: Build-IaC
    runs-on: ubuntu-20.04

    steps:
      - name: Creation dossier artifact
        run: |
          mkdir TemplateJSON

      - name: Recuperation de artefact
        uses: actions/download-artifact@v2
        with:
          name: arm_template
          path: TemplateJSON

      - name: Login Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Creation du RG
        run: |
          az group create --name ${{ env.RG_NAME }} --location ${{ env.LOCATION }}   

      - name: WhatIf json
        run: |
          az deployment group what-if --resource-group 'rg-test-tdf' --template-file ./TemplateJSON/main.json --parameters 'serverNameDB=${{ env.SERVER_NAME_DB }}' 'dbName=${{ env.DB_NAME }}' 'userName=${{ env.USER_NAME }}' 'Password=${{ env.PASSWORD }}' 'planName=${{ env.PLAN_NAME }}' 'siteName=${{ env.SITE_NAME }}'
  Deploy-IAC:
    needs: Ckeck-IaC
    runs-on: ubuntu-20.04

    steps:
      - name: Creation dossier artifact
        run: |
          mkdir TemplateJSON

      - name: Recuperation de artefact
        uses: actions/download-artifact@v2
        with:
          name: arm_template
          path: TemplateJSON

      - name: Login Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploiement du template
        run: |
          az deployment group create --resource-group ${{ env.RG_NAME}} --template-file ./TemplateJSON/main.json --parameters 'serverNameDB=${{ env.SERVER_NAME_DB }}' 'dbName=${{ env.DB_NAME }}' 'userName=${{ env.USER_NAME }}' 'Password=${{ env.PASSWORD }}' 'planName=${{ env.PLAN_NAME }}' 'siteName=${{ env.SITE_NAME }}'

      - name: network rule (c'est moche)
        run: |
          az mysql server firewall-rule create --resource-group ${{ env.RG_NAME}} --server ${{ env.SERVER_NAME_DB }} --name AllowAppService --start-ip-address 0.0.0.0 --end-ip-address 255.255.255.255

      - name: Slack Notification du déploiement
        uses: tokorom/action-slack-incoming-webhook@main
        env:
          INCOMING_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          text: Action GitHub -> "repo demo-tdf " -> Approuve le deploiement
          attachments: |
            [
              {
                "color": "good",
                "author_name": "${{ github.actor }}",
                "author_icon": "${{ github.event.sender.avatar_url }}"
              }
            ]      
  Build-App:
    runs-on: ubuntu-20.04
    steps:

      - name: Repuperation du repo
        uses: actions/checkout@v2

      - name: Perform Scan CredScan & Java
        uses: ShiftLeftSecurity/scan-action@master
        with:
          type: "credscan,java"

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Creation du package ROOT.war avec Maven
        run: |
          mvn --batch-mode --update-snapshots verify

      - name: Copie du fichier artefacts ROOT.war 
        run: | 
          mkdir warfile && cp target/*.war warfile

      - name: Publication du fichier ROOT.war en artefact  
        uses: actions/upload-artifact@v2
        with:
          name: Package-WAR
          path: warfile
  Deploy-App:
    runs-on: ubuntu-20.04
    needs:
      - Build-App
      - Deploy-IAC
    environment:
      name: Test-Dev
    steps:

      - name: Creation dossier artifact
        run: |
          mkdir warfile

      - name: Recuperation des artefacts
        uses: actions/download-artifact@v2
        with:
          name: Package-WAR
          path: warfile

      - name: Azure Login
        uses: Azure/login@v1
        with:    
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploiement de l'application JAVA
        uses: azure/webapps-deploy@v2
        id: deploy-to-azure
        with:
          app-name: ${{ env.SITE_NAME }}
          package: ./warfile/ROOT.war 