name: Deploiement SmartHotel360

on: workflow_dispatch

env:
  RG_NAME: rg-test-tdf
  LOCATION: westeurope
  SERVER_NAME_DB: smh360mysql40406cc
  DB_NAME: hotel_coupon
  USER_NAME: sqladmin
  PASSWORD: P2ssw0rd@123
  PLAN_NAME: smh360plan
  SITE_NAME: smh360webd4041cc

jobs:
  Build-IaC:
    runs-on: ubuntu-20.04

    steps:
      - name: recuperation du repository
        uses: actions/checkout@v2

      - name: build json
        run: |
          az bicep build --files ./bicep/main.bicep

      - name: Artifacts json
        uses: actions/upload-artifact@v1
        with:
          name: arm_template
          path: ./bicep/main.json
  Ckeck-IaC:
    needs: Build-IaC
    runs-on: ubuntu-20.04

    steps:
      - name: Creation dossier artifact
        run: |
          mkdir TemplateJSON

      - name: Recuperation de artefact
        uses: actions/download-artifact@v2
        with:
          name: arm_template
          path: TemplateJSON

      - name: Login Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Creation du RG
        run: |
          az group create --name ${{ env.RG_NAME }} --location ${{ env.LOCATION }}   

      - name: WhatIf json
        run: |
          az deployment group what-if --resource-group 'rg-test-tdf' --template-file ./TemplateJSON/main.json --parameters 'serverNameDB=${{ env.SERVER_NAME_DB }}' 'dbName=${{ env.DB_NAME }}' 'userName=${{ env.USER_NAME }}' 'Password=${{ env.PASSWORD }}' 'planName=${{ env.PLAN_NAME }}' 'siteName=${{ env.SITE_NAME }}'

  Build-App:
    runs-on: ubuntu-20.04
    steps:

      - name: Repuperation du repo
        uses: actions/checkout@v2

      - name: Perform Scan CredScan & Java
        uses: ShiftLeftSecurity/scan-action@master
        with:
          type: "credscan,java"

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Creation du package ROOT.war avec Maven
        run: |
          mvn --batch-mode --update-snapshots verify

      - name: Copie du fichier artefacts ROOT.war 
        run: | 
          mkdir warfile && cp target/*.war warfile

      - name: Publication du fichier ROOT.war en artefact  
        uses: actions/upload-artifact@v2
        with:
          name: Package-WAR
          path: warfile